version: '3'
services:
  spring_boot:
    build: ./spring_boot
    container_name: lesson-1_java
    ports:
      - '9090:8080'
    volumes:
      - ../src/lesson1:/workspace
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      - MYAPP_JDBC_URL=jdbc:postgresql://db:5432/lesson_1
      - MYAPP_JDBC_USER=admin
      - MYAPP_JDBC_PASS=admin
  db:
    build: ./db
    container_name: lesson-1_db
    ports:
      - '5432:5432'
    volumes:
      - ../src/.mock/data:/var/lib/postgresql/data
      - ../src/.mock/init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_DB: lesson_1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
